server:
  port: 8083

spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://localhost:3306/feedbox?serverTimezone=Asia/Seoul
    username: feedbox_user
    password: feedbox_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: none
  kafka:
    bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
  data:
    mongodb:
      uri: mongodb://user:password@localhost:27017/feedbox?authSource=admin
    elasticsearch:
      host: localhost
      port: 9200

userdata-server:
  url: http://localhost:8088